name = 'RPG Adventure'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[compilerOptions]
    pwaEnabled = true
    basePath = '/Sketch/'

[start]
    map = 'simplemap'
    graphic = 'hero'
    hitbox = [16, 16]